# Configuration file for the Sphinx documentation builder.
#
# Full list of options can be found in the Sphinx documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------


project = 'BRIOM Docs'
copyright = '2026, Уфа, Girfanov.Ayrat@yandex.ru'
author = 'Girfanov.Ayrat@yandex.ru'
# The full version, including alpha/beta/rc tags
master_doc = 'index'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

extensions = [
    'sphinx_rtd_theme',
    'sphinx.ext.autosectionlabel',
]
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ru'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'logo_only': False,
    'display_version': True,
    'style_external_links': False,
    # Toc options
    'collapse_navigation': True,
    'style_nav_header_background': '#2F2F2F',
    'sticky_navigation': False,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = [
    'css/theme_overrides.css',
]
#html_logo = 'ai16.png'

#html_favicon = 'favicon.svg'

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
html_use_index = False

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

#-- Options for LaTeX output ---------------------------------------------

latex_maketitle = r'''
\begin{titlepage}
\sphinxlogo
\end{titlepage}
'''

# allow utf8 characters
latex_elements = {
    'sphinxsetup': '',
    'passoptionstopackages': r'\PassOptionsToPackage{table}{xcolor}',
    'preamble': '',
    'maketitle': latex_maketitle,
    'figure_align': 'htpb',
    'pointsize': '10pt',
    'papersize': 'a4paper',
}
# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = 'images/ai/ai.png'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_use_parts = True

# If true, show page references after internal links.
latex_show_pagerefs = True

# If true, show URL addresses after external links.
latex_show_urls = False

# Documents to append as an appendix to all manuals.
latex_appendices = []

# If false, no module index is generated.
latex_domain_indices = True

latex_engine = 'xelatex'  

latex_theme = 'howto'


